// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://uflbwsegfnoorqoiltif.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVmbGJ3c2VnZm5vb3Jxb2lsdGlmIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQzMTQ2ODcsImV4cCI6MjA1OTg5MDY4N30.E9PFQqKrNXSUinvTHrbAmoSNLoPbUIIf-tQbbN9bGSs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);